name: pila
channels:
  - anaconda
  - plotly
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - asttokens=2.0.5
  - autopep8=2.0.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=1.15.1
  - click=8.1.7
  - contourpy=1.2.0
  - cpuonly=2.0
  - cryptography=41.0.3
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.37
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.15.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.2.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - numba=0.61.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=23.1
  - pandas=1.5.3
  - parso=0.8.3
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - plotly=5.14.1
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=3.20.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pygments=2.15.1
  - pynndescent=0.5.13
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.2.0
  - scipy=1.10.1
  - seaborn=0.12.2
  - sentry-sdk=1.9.0
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - tenacity=8.2.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.0.0
  - torchdiffeq=0.2.2
  - torchvision=0.15.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - umap-learn=0.5.9.post2
  - urllib3=1.26.18
  - wandb=0.15.1
  - wcwidth=0.2.5
  - wheel=0.41.2
  - x264=1!157.20191217
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - affine==2.4.0
      - attrs==25.1.0
      - charset-normalizer==2.1.1
      - click-plugins==1.1.1
      - cligj==0.7.2
      - et-xmlfile==2.0.0
      - geopandas==1.0.1
      - openpyxl==3.1.5
      - psutil==5.9.5
      - ptvsd==4.3.2
      - pykalman==0.9.7
      - pyogrio==0.10.0
      - pyproj==3.7.1
      - rasterio==1.4.3
      - setproctitle==1.3.2
      - shapely==2.0.7
      - smmap==5.0.0
      - xml-python==0.4.3
